title: Data Interview Blogs
author: Vanshaj Gupta
description: Daily database interview prep

# Use GitHub's default theme
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:title/
